// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu802GvulaX2UGPQ0Nx7I5gB-X6JVfe5I',
    appId: '1:236150161720:web:6b5be538abf3e7570381cd',
    messagingSenderId: '236150161720',
    projectId: 'temu-ekspor-application',
    authDomain: 'temu-ekspor-application.firebaseapp.com',
    storageBucket: 'temu-ekspor-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMJeXzr2WnA9AQQhYkAuB_lIjLIGIjJI',
    appId: '1:236150161720:android:fb28becbef45f34a0381cd',
    messagingSenderId: '236150161720',
    projectId: 'temu-ekspor-application',
    storageBucket: 'temu-ekspor-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzbeOZ5OnxyHZrKvsX89eenqeOSvOsG7k',
    appId: '1:236150161720:ios:39afc33e64e15d890381cd',
    messagingSenderId: '236150161720',
    projectId: 'temu-ekspor-application',
    storageBucket: 'temu-ekspor-application.appspot.com',
    iosBundleId: 'com.example.temuEksporApplication',
  );
}
